apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: mkdocs
spec: 
  selector: 
    matchLabels: 
      app: mkdocs 
  replicas: 1 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: mkdocs 
    spec: 
      containers: 
      - name: mkdocs 
        image: ghenriquee/dockerhub:mkdocsteste
        ports: 
        - containerPort: 8000

---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: mkdocs-service 
spec: 
  selector: 
    app: mkdocs 
  ports: 
  - protocol: TCP 
    port: 8000
    targetPort: 8000
  type: ClusterIP 